version: '3'

services:
  db:
    platform: linux/x86_64
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nest
    ports:
      - "5434:5432"
    volumes:
      - nest_data:/var/lib/postgres
volumes:
  nest_data: